TIEMPO_VERDE = 4
TIEMPO_AMARILLO = 2
TIEMPO_ROJO = TIEMPO_VERDE + TIEMPO_AMARILLO
CICLOS_TOTALES = 10

VIAS_PARES = [["NORTE", "SUR"], ["ESTE", "OESTE"]]

VELOCIDAD_AVANCE = 5
POSICION_CRUCE = 200
POSICION_SALIDA = 400 

VIAS = ["NORTE", "SUR", "ESTE", "OESTE"]
DISTANCIA_ENTRE_VEHICULOS = 30
PASO_AVANCE = 5
POSICION_FINAL = 200 
